name: Python app build, test, and deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yourdockerusername/python-app:latest

    - name: Test app
      run: |
        pip install pytest
        pytest tests.py

    - name: Deploy app
      uses: appleboy/ssh-action@master
      with:
        host: yourserver.com
        username: yourusername
        password: ${{ secrets.PASSWORD }}
        script: |
          docker stop python-app || true
          docker rm python-app || true
          docker pull yourdockerusername/python-app:latest
          docker run -d -p 8000:8000 --name python-app yourdockerusername/python-app:latest

