name: Docker Build, Test, and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: nome_da_sua_imagem:latest

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Docker image
        run: |
          docker pull nome_da_sua_imagem:latest

      - name: Run tests
        run: |
          docker run nome_da_sua_imagem python -m unittest discover

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nome_da_sua_imagem:latest
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          host: your-server-hostname-or-ip
          username: your-ssh-username
          password: ${{ secrets.SSH_PASSWORD }}
          port: your-ssh-port
          script: |
            docker stop nome_da_sua_imagem || true
            docker rm nome_da_sua_imagem || true
            docker pull docker.pkg.github.com/your-github-username/your-repository/nome_da_sua_imagem:latest
            docker run -d -p 8000:8000 --name nome_da_sua_imagem docker.pkg.github.com/your-github-username/your-repository/nome_da_sua_imagem:latest
