name: Pipeline para Build, Test e Deploy de Aplicação Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Build da imagem Docker
        run: docker build -t imagem-minha:latest .

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
            docker pull ubuntu
      - name: Pull da imagem para o Docker Hub
        run: docker pull imagem-minha:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
           docker run -d -p 5000:5000 --name meuregistro registry:2

      - name: Pull da imagem do Docker Hub
        run: docker pull imagem-minha:latest
         docker run -d -p 5000:5000 --name meuregistro registry:2

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Rodar container com a imagem
        run: docker run -d -p 5000:5000 minha_imagem
