steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Login to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build Docker image
    uses: docker/build-push-action@v2
    with:
      context: .
      push: false
      tags: your-docker-username/your-docker-repo:latest
steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Download Docker image
    run: |
      docker pull your-docker-username/your-docker-repo:latest

  - name: Run tests
    run: |
      docker run your-docker-username/your-docker-repo python -m unittest discover
steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Login to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build and push Docker image
    uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: your-docker-username/your-docker-repo:latest

  - name: Deploy Docker container
    uses: appleboy/ssh-action@master
    with:
      host: your-server-hostname-or-ip
      username: your-ssh-username
      password: ${{ secrets.SSH_PASSWORD }}
      port: your-ssh-port
      script: |
        docker stop your-docker-container-name || true
        docker rm your-docker-container-name || true
        docker pull your-docker-username/your-docker-repo:latest
        docker run -d -p 8000:8000 --name your-docker-container-name your-docker-username/your-docker-repo:latest
