name: Pipeline para Build, Test e Deploy de Aplicação Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Build da imagem Docker
        run: docker build -t imagem-minha:latest .

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run SAST Analysis via Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          #config: python.lang.security.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build Docker image
        run: docker build -t  ${{secrets.DOCKERHUB_USER}/imagem-minha:latest .

      - name: Push da imagem para o registro
        run: |
          docker tag imagem-minha:latest localhost:5000/imagem-minha:latest
          docker push localhost:5000/imagem-minha:latest

      - name: Pull da imagem do registro
        run: docker pull localhost:5000/imagem-minha:latest 

      - name: Rodar container com a imagem
        run: docker run -d -p 8080:8080 localhost:5000/imagem-minha:latest
